/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellCartRouteImport } from './routes/_shell/cart'
import { Route as ShellCheckoutRouteImport } from './routes/_shell/checkout'
import { Route as ShellContactRouteImport } from './routes/_shell/contact'
import { Route as ShellOrderConfirmedRouteImport } from './routes/_shell/order-confirmed'
import { Route as ShellShopRouteImport } from './routes/_shell/shop'
import { Route as ApiRatesRouteImport } from './routes/api/rates'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ClassicIndexRouteImport } from './routes/classic/index'
import { Route as ClassicCartRouteImport } from './routes/classic/cart'
import { Route as ClassicCheckoutRouteImport } from './routes/classic/checkout'
import { Route as ClassicOrderConfirmedRouteImport } from './routes/classic/order-confirmed'
import { Route as ClassicShopRouteImport } from './routes/classic/shop'
import { Route as ShellProductSlugRouteImport } from './routes/_shell/product/$slug'
import { Route as ClassicProductSlugRouteImport } from './routes/classic/product/$slug'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCartRoute = ShellCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCheckoutRoute = ShellCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContactRoute = ShellContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrderConfirmedRoute = ShellOrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShopRoute = ShellShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ShellRoute,
} as any)
const ApiRatesRoute = ApiRatesRouteImport.update({
  id: '/api/rates',
  path: '/api/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicIndexRoute = ClassicIndexRouteImport.update({
  id: '/classic/',
  path: '/classic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicCartRoute = ClassicCartRouteImport.update({
  id: '/classic/cart',
  path: '/classic/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicCheckoutRoute = ClassicCheckoutRouteImport.update({
  id: '/classic/checkout',
  path: '/classic/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicOrderConfirmedRoute = ClassicOrderConfirmedRouteImport.update({
  id: '/classic/order-confirmed',
  path: '/classic/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicShopRoute = ClassicShopRouteImport.update({
  id: '/classic/shop',
  path: '/classic/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProductSlugRoute = ShellProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ClassicProductSlugRoute = ClassicProductSlugRouteImport.update({
  id: '/classic/product/$slug',
  path: '/classic/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/cart': typeof ShellCartRoute
  '/checkout': typeof ShellCheckoutRoute
  '/contact': typeof ShellContactRoute
  '/order-confirmed': typeof ShellOrderConfirmedRoute
  '/shop': typeof ShellShopRoute
  '/api/rates': typeof ApiRatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/classic/cart': typeof ClassicCartRoute
  '/classic/checkout': typeof ClassicCheckoutRoute
  '/classic/order-confirmed': typeof ClassicOrderConfirmedRoute
  '/classic/shop': typeof ClassicShopRoute
  '/classic/': typeof ClassicIndexRoute
  '/product/$slug': typeof ShellProductSlugRoute
  '/classic/product/$slug': typeof ClassicProductSlugRoute
}
export interface FileRoutesByTo {
  '/cart': typeof ShellCartRoute
  '/checkout': typeof ShellCheckoutRoute
  '/contact': typeof ShellContactRoute
  '/order-confirmed': typeof ShellOrderConfirmedRoute
  '/shop': typeof ShellShopRoute
  '/api/rates': typeof ApiRatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/classic/cart': typeof ClassicCartRoute
  '/classic/checkout': typeof ClassicCheckoutRoute
  '/classic/order-confirmed': typeof ClassicOrderConfirmedRoute
  '/classic/shop': typeof ClassicShopRoute
  '/': typeof ShellIndexRoute
  '/classic': typeof ClassicIndexRoute
  '/product/$slug': typeof ShellProductSlugRoute
  '/classic/product/$slug': typeof ClassicProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/cart': typeof ShellCartRoute
  '/_shell/checkout': typeof ShellCheckoutRoute
  '/_shell/contact': typeof ShellContactRoute
  '/_shell/order-confirmed': typeof ShellOrderConfirmedRoute
  '/_shell/shop': typeof ShellShopRoute
  '/api/rates': typeof ApiRatesRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/classic/cart': typeof ClassicCartRoute
  '/classic/checkout': typeof ClassicCheckoutRoute
  '/classic/order-confirmed': typeof ClassicOrderConfirmedRoute
  '/classic/shop': typeof ClassicShopRoute
  '/_shell/': typeof ShellIndexRoute
  '/classic/': typeof ClassicIndexRoute
  '/_shell/product/$slug': typeof ShellProductSlugRoute
  '/classic/product/$slug': typeof ClassicProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmed'
    | '/shop'
    | '/api/rates'
    | '/api/stripe-webhook'
    | '/classic/cart'
    | '/classic/checkout'
    | '/classic/order-confirmed'
    | '/classic/shop'
    | '/classic/'
    | '/product/$slug'
    | '/classic/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-confirmed'
    | '/shop'
    | '/api/rates'
    | '/api/stripe-webhook'
    | '/classic/cart'
    | '/classic/checkout'
    | '/classic/order-confirmed'
    | '/classic/shop'
    | '/'
    | '/classic'
    | '/product/$slug'
    | '/classic/product/$slug'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/cart'
    | '/_shell/checkout'
    | '/_shell/contact'
    | '/_shell/order-confirmed'
    | '/_shell/shop'
    | '/api/rates'
    | '/api/stripe-webhook'
    | '/classic/cart'
    | '/classic/checkout'
    | '/classic/order-confirmed'
    | '/classic/shop'
    | '/_shell/'
    | '/classic/'
    | '/_shell/product/$slug'
    | '/classic/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ApiRatesRoute: typeof ApiRatesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ClassicCartRoute: typeof ClassicCartRoute
  ClassicCheckoutRoute: typeof ClassicCheckoutRoute
  ClassicOrderConfirmedRoute: typeof ClassicOrderConfirmedRoute
  ClassicShopRoute: typeof ClassicShopRoute
  ClassicIndexRoute: typeof ClassicIndexRoute
  ClassicProductSlugRoute: typeof ClassicProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cart': {
      id: '/_shell/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShellCartRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/checkout': {
      id: '/_shell/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShellCheckoutRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contact': {
      id: '/_shell/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ShellContactRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/order-confirmed': {
      id: '/_shell/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof ShellOrderConfirmedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/shop': {
      id: '/_shell/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShellShopRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/rates': {
      id: '/api/rates'
      path: '/api/rates'
      fullPath: '/api/rates'
      preLoaderRoute: typeof ApiRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/': {
      id: '/classic/'
      path: '/classic'
      fullPath: '/classic/'
      preLoaderRoute: typeof ClassicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/cart': {
      id: '/classic/cart'
      path: '/classic/cart'
      fullPath: '/classic/cart'
      preLoaderRoute: typeof ClassicCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/checkout': {
      id: '/classic/checkout'
      path: '/classic/checkout'
      fullPath: '/classic/checkout'
      preLoaderRoute: typeof ClassicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/order-confirmed': {
      id: '/classic/order-confirmed'
      path: '/classic/order-confirmed'
      fullPath: '/classic/order-confirmed'
      preLoaderRoute: typeof ClassicOrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic/shop': {
      id: '/classic/shop'
      path: '/classic/shop'
      fullPath: '/classic/shop'
      preLoaderRoute: typeof ClassicShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/product/$slug': {
      id: '/_shell/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ShellProductSlugRouteImport
      parentRoute: typeof ShellRoute
    }
    '/classic/product/$slug': {
      id: '/classic/product/$slug'
      path: '/classic/product/$slug'
      fullPath: '/classic/product/$slug'
      preLoaderRoute: typeof ClassicProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellCartRoute: typeof ShellCartRoute
  ShellCheckoutRoute: typeof ShellCheckoutRoute
  ShellContactRoute: typeof ShellContactRoute
  ShellOrderConfirmedRoute: typeof ShellOrderConfirmedRoute
  ShellShopRoute: typeof ShellShopRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProductSlugRoute: typeof ShellProductSlugRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCartRoute: ShellCartRoute,
  ShellCheckoutRoute: ShellCheckoutRoute,
  ShellContactRoute: ShellContactRoute,
  ShellOrderConfirmedRoute: ShellOrderConfirmedRoute,
  ShellShopRoute: ShellShopRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellProductSlugRoute: ShellProductSlugRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ApiRatesRoute: ApiRatesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ClassicCartRoute: ClassicCartRoute,
  ClassicCheckoutRoute: ClassicCheckoutRoute,
  ClassicOrderConfirmedRoute: ClassicOrderConfirmedRoute,
  ClassicShopRoute: ClassicShopRoute,
  ClassicIndexRoute: ClassicIndexRoute,
  ClassicProductSlugRoute: ClassicProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
